export const SupportItems = [
  {
    id: 1,
    heading: "AWARD WINNING MARKETING PROGRAMS",
    listOne: "Online Marketing Asset Library",
    listTwo: "Branded Merchandise",
    listThree: "Media Planning Tools",
    listFour: "Exclusive Digital Content",
    listFive: "Quarterly Launch Calls",
    listSix: "Gold’s Gym Fitness Institute",
    listSeven: "CRM Program",
    listEight: "Online Marketing Asset Library",
  },
  {
    id: 2,
    heading: "STATE-OF-THE-ART TRAINING & SUPPORT",
    listOne: "Annual Convention",
    listTwo: "Associate Training",
    listThree: "Gold’s Connect Internet",
    listFour: "Brand Management",
    listFive: "Training Manuals",
    listSix: "Construction tools and models",
    listSeven: "Gold’s Gym University",
    listEight: "Gold’s Gym Fitness Institute",
  },
];
